// src/app/main/contact-me/contact-me.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact-me',
  standalone: true,
  imports: [],
  templateUrl: './contact-me.component.html'
})
export class ContactMeComponent {

}

<section id="contact-me" class="bg-[url('./assets/img/photograph_3.jpg')] bg-no-repeat bg-fixed bg-center bg-cover">

    <section 
    class="3xl:px-96 3xl:py-20 xxs:px-10 xxs:gap-7 2xl:gap-10 bg-gray-200/85 3xl:h-[47vh] xxs:h-[35vh] xxs:min-h-[200px] 3xl:min-h-[330px] flex items-center justify-center flex-col leading-relaxed tracking-wider xxs:text-center lg:text-start lg:h-[40vh] lg:min-h-[230px] 2xl:min-h-[300px]"
    >
        <h1 class="xxs:text-lg md:text-2xl 3xl:self-start 2xl:text-4xl 3xl:text-5xl tracking-widest text-orange-700 scale-y-125">Let's Connect!</h1>
        <p class="text-[rgba(4,47,46,1)] 3xl:self-start scale-y-[1.25] xxs:text-sm 2xl:text-2xl">Let's make something great together!</p>
    </section>

    <section 
        class="flex lg:h-[53vh] lg:min-h-[275px] items-center justify-center 3xl:py-20 xxs:gap-5 3xl:gap-10 flex-col 3xl:px-96 xxs:px-10 md:px-20 xl:px-45 bg-gray-200 xxs:h-[58vh] xxs:min-h-[375px] 3xl:h-[46vh] 2xl:min-h-[300px] 3xl:min-h-[310px] text-[rgba(4,47,46,1)] tracking-wider"
    >

        <p 
            class="2xl:text-sm xxs:text-xs"
        >
            I'd love to hear from you. Whether you have a project in mind, a question, or just want to say hello, feel free to reach out. I'm always open to exciting opportunities and collaborations.
        </p>
    </section>


    <section [ngClass]="{
        'xxs:min-h-[745px] xs:min-h-[685px] lg:min-h-[630px] xl:h-[75vh] 3xl:h-[75vh] 3xl:min-h-[618px]' : !hasError() || !isSubmit(),
        '3xl:h-[85vh] 3xl:min-h-[700px]' : hasError() || isSubmit()
    }"
    class="text-gray-300  xxs:h-screen xxs:flex 2xl:block justify-center items-center p-20 3xl:px-96 xxs:p-10 xxs:px-5 bg-gray-200 w-full md:px-20 xl:px-45">

            <form 
            (ngSubmit)="onSubmit()"
            [formGroup]="contactMeForm" class="h-full flex flex-col xxs:justify-between p-10 xl:px-10 xxs:px-5 w-full px-20 rounded-lg bg-zinc-800">

                <h2 class="font-bold text-orange-800 3xl:text-2xl xxs:text-lg tracking-wider">Start a Conversation</h2>

                @if(isSubmit()){
                    <div [ngClass]="{
                        'text-red-700' : finalMessage().typeOfMessage == 'error',
                        'text-green-700' : finalMessage().typeOfMessage == 'success'
                    }"
                    class="transition-opacity duration-3000 opacity-100 xxs:text-xs 2xl:text-sm">
                        <small>{{finalMessage().message}}</small>
                    </div>
                    
                }

                <section class="xl:flex xxs:block lg:h-[75%] xxs:h-[80%] items-center justify-center w-full 2xl:gap-10 xl:gap-4 3xl:gap-12">

                    <section class="xl:h-full justify-start xxs:text-xs 2xl:text-sm xxs:w-full  flex flex-col w-[55%] xxs:h-[60%] xxs:mb-4 xl:mb-0">

                        <section class="flex items-center w-full text-black mb-5">
                            <input formControlName="fullName" name="fullName" class="outline-0 rounded-md py-2 pl-2 w-[50%] mr-2 xs:text-xs 2xl:text-sm bg-gray-300" type="text" placeholder="Full name*" required>
                            <input formControlName="email" name="email" class="outline-0 rounded-md py-2 pl-2 w-[50%] xs:text-xs 2xl:text-sm bg-gray-300" type="email" placeholder="Your email address*" required>  
                        </section>
            
                        <section id="panis" class="flex h-full text-black">
                            <textarea formControlName="message" name="message" class="outline-0 w-full h-full rounded-md py-2 pl-2 xs:text-xs 2xl:text-sm resize-none bg-gray-300" id="message" name="message" placeholder="Feel free to share details about your inquiry, whether it's about a project, job opportunity, or anything else you'd like to discuss.*" required></textarea>
                        </section>
    
                    </section>

                    <section class="xxs:h-[35%] xl:h-[45%] 2xl:w-[60%] xxs:w-full flex flex-col xxs:justify-around 2xl:justify-center 2xl:gap-7">
                        <section class="xxs:text-xs 2xl:text-sm">
                            <h2 class="text-orange-700 mb-2">What about pricing?</h2>
                            <p>Pricing details vary depending on the project scope, requirements, and timelines. Feel free to share your project specifics, and I'll provide a tailored quote.</p>
                        </section>
            
                        <section class="xxs:text-xs 2xl:text-sm">
                            <h2 class="text-orange-700 mb-2">What about working status?</h2>
                            <p>I'm currently open to new opportunities and projects. If you have a project in mind, feel free to reach out.</p>
                        </section>
                    </section>
                </section>

                @if(contactMeForm.controls['fullName'].touched || contactMeForm.controls['email'].touched || contactMeForm.controls['message'].touched){

                    @if(contactMeForm.controls['fullName'].errors?.['required'] && contactMeForm.controls['email'].errors?.['required'] && contactMeForm.controls['message'].errors?.['required']){
                        <div class=" text-red-700 xxs:text-xs 2xl:text-sm transition-opacity duration-3000">
                            <small>All fields are required.</small>
                        </div>
                    }
                    @else if(contactMeForm.controls['fullName'].errors?.['minlength']){
        
                        <div class="text-red-700 xxs:text-xs 2xl:text-sm transition-opacity duration-3000">
                            <small>Your full name must be at least 5 characters long.</small>
                        </div>
                    }
                    @else if (contactMeForm.controls['email'].errors?.['email']) {
                        <div class="transition-opacity duration-3000text-red-700 xxs:text-xs 2xl:text-sm">
                            <small>{{'Invalid email format. Please enter a valid email address (e.g., name@example.com).'}}</small>
                        </div>
                    }
                    @else if (contactMeForm.controls['message'].errors?.['minlength']) {
                  
                        <div class="transition-opacity duration-3000 text-red-700 xxs:text-xs 2xl:text-sm">
                            <small>Your message must be at least 10 characters long.</small>
                        </div>
                    }
                    @else if (contactMeForm.controls['message'].errors?.['maxlength']) {
                        
                        <div class="transition-opacity duration-3000 text-red-700 xxs:text-xs 2xl:text-sm">
                            <small>Your message must be no longer than 500 characters.</small>
                        </div>
                    }
                }

                <section class="flex xxs:flex-col xl:flex-row xxs:h-[8.5%] xl:h-[12%] xl:items-center xl:gap-7 xxs:justify-between xl:justify-start tracking-wide xxs:text-xs 2xl:text-sm">
                    <button [ngClass]="contactMeForm.invalid ? '' : 'hover:bg-blue-950 cursor-pointer'" [disabled]="contactMeForm.invalid" type="submit" class="xl:p-4 xxs:p-2 xxs:w-[50%] xs:w-[40%] md:w-[35%] lg:w-[30%] xl:w-[20%] shadow-md rounded-md bg-blue-900 xxs:mb-3 xl:mb-0">Send message</button>
                    <div>
                        <span>I will respond after 1-2 working days.</span>
                    </div>
                </section>
    
            </form>
    
            <!-- <div class="w-[35%] h-[33.7vh] flex flex-col justify-center">
                <section class="mb-7 xs:text-xs 2xl:text-base">
                    <h2 class="text-orange-700 mb-2">What about pricing?</h2>
                    <p>Pricing details vary depending on the project scope, requirements, and timelines. Feel free to share your project specifics, and I'll provide a tailored quote.</p>
                </section>
    
                <section class="xs:text-xs 2xl:text-base">
                    <h2 class="text-orange-700 mb-2">What about working status?</h2>
                    <p>I'm currently open to new opportunities and projects. If you have a project in mind, feel free to reach out.</p>
                </section>
            </div> -->
        

        
    </section>


    <!-- <section class="text-red-700 font-bold text-center">
        <h2 class="xs:text-xl lg:text-3xl md:text-2xl 3xl:text-4xl 2xl:mb-4 tracking-wider mb-5">Contact Me</h2>
        <h1>UNDER CONSTRUCTION</h1> 
    </section> -->

</section>

// app/pages/contact-me/index.vue
<template>
  <div>
    <Custom :image="'/img/photography/photograph_3.webp'">
      <Head
        :title="'Contact Me'"
        :description="`Explore Jon's projects, tech stack, and resume. Specializing in Nuxt, Angular, Spring Boot and Laravel.`"
      />

      <Toast ref="toastRef" />

      <section>
        <div>
          <Hero
            :subtitle="'Collaboration starts with a conversation'"
            :title="`Let’s Build Something Together`"
            :style="'bg-gray-200/90'"
          />
        </div>
      </section>

      <section>
        <div
          class="flex items-center justify-center gap-10 xl:gap-4 flex-col xl:flex-row h-80 xl:h-96 bg-gray-50 w-full px-4 py-10 xl:px-52"
        >
          <p class="text-xs 2xl:text-sm tracking-widest text-teal-950">
            I'd love to hear from you. Whether you have a project in mind, a
            question, or just want to say hello, feel free to reach out. I'm
            always open to exciting opportunities and collaborations.
          </p>
        </div>
      </section>

      <section>
        <div
          class="flex items-center justify-center px-4 py-10 xl:px-48 w-full"
        >
          <form
            @submit.prevent="handleSubmit"
            class="rounded-xl bg-zinc-900 tracking-widest space-y-7 p-8 w-full"
          >
            <!-- Heading -->
            <h2 class="text-orange-700 font-semibold text-xl">
              Start a Conversation
            </h2>

            <div class="flex flex-col xl:flex-row gap-7 w-full">
              <!-- Left Side: Form -->
              <div
                class="flex flex-col gap-4 flex-1 w-full xl:h-60 text-xs 2xl:text-sm"
              >
                <!-- Name + Email -->
                <div class="flex flex-col md:flex-row gap-4 w-full">
                  <input
                    v-model="form.fullName"
                    class="flex-1 py-2 px-4 rounded-md outline-0 bg-gray-50 placeholder-gray-500 text-teal-950"
                    placeholder="Enter your full name*"
                    type="text"
                    required
                  />
                  <input
                    v-model="form.email"
                    class="flex-1 py-2 px-4 placeholder-gray-500 text-teal-950 rounded-md outline-0 bg-gray-50"
                    placeholder="Enter your email address*"
                    type="email"
                    required
                  />
                </div>

                <!-- Message -->
                <textarea
                  v-model="form.message"
                  required
                  class="w-full py-2 h-48 xl:h-full px-4 rounded-md outline-0 placeholder-gray-500 text-teal-950 bg-gray-50 resize-none"
                  placeholder="Enter your message*"
                ></textarea>
              </div>

              <!-- Right Side: Info -->
              <div
                class="flex flex-col items-center justify-center gap-6 flex-1 text-xs 2xl:text-sm xl:h-60"
              >
                <div class="space-y-2">
                  <h3 class="text-orange-700 text-lg">What about pricing?</h3>
                  <p>
                    Pricing depends on the project scope and timeline. Let me
                    know your ideas and I’ll send a custom quote.
                  </p>
                </div>

                <div class="space-y-2">
                  <h3 class="text-orange-700 text-lg">
                    What about working status?
                  </h3>
                  <p>
                    I’m currently working full-time, but I’m still open to
                    freelance projects and collaborations. Let’s create
                    something awesome together!
                  </p>
                </div>
              </div>
            </div>

            <div class="flex flex-col md:flex-row items-center gap-3">
              <button
                class="bg-orange-700 text-xs 2xl:text-sm text-white px-5 py-2 rounded-md shadow-md hover:bg-orange-800 transition-all duration-300"
              >
                Send Message
              </button>
              <small class="text-gray-300"
                >I will respond within 1-2 working days.</small
              >
            </div>
          </form>
        </div>
      </section>
    </Custom>
  </div>
</template>

<script lang="ts" setup>
import Head from "~/components/Head.vue";
import Custom from "~/layouts/Custom.vue";
import { contactMeService } from "./service/contact-me.service";
import Toast from "~/components/Toast.vue";

const toastRef = ref<InstanceType<typeof Toast>>();
const form = ref({
  email: "",
  fullName: "",
  message: "",
});

const handleSubmit = async () => {
  try {
    const response = await contactMeService().sendInquiry(form.value);

    if (response) {
      toastRef.value?.show("Message sent successfully!", "success");
      form.value = { email: "", fullName: "", message: "" };
    }
  } catch (e: any) {
    console.log(e);

    const message =
      e?.data?.message ||
      e?.message ||
      e?.statusMessage ||
      "Failed to send message.";

    toastRef.value?.show(message, "error");
  }
};
</script>

<style></style>
