// src/app/main/hobbies/hobbies.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-hobbies',
  standalone: true,
  imports: [],
  templateUrl: './hobbies.component.html'
})
export class HobbiesComponent {

}

<section id="projects" class="bg-[url('./assets/img/arbell_3.png')] min-h-screen bg-no-repeat bg-fixed bg-center bg-cover">

    <section 
    class="3xl:px-96 3xl:py-20 xxs:px-10 xxs:gap-7 2xl:gap-10 bg-gray-200/85 3xl:h-[47vh] xxs:h-[35vh] xxs:min-h-[200px] 3xl:min-h-[330px] flex items-center justify-center flex-col leading-relaxed tracking-wider xxs:text-center lg:text-start lg:h-[40vh] lg:min-h-[230px] 2xl:min-h-[300px]"
    >
        <h1 class="xxs:text-lg md:text-2xl 3xl:self-start 2xl:text-4xl 3xl:text-5xl tracking-widest text-orange-700 scale-y-125">My Creative Side</h1>
        <p class="text-[rgba(4,47,46,1)] 3xl:self-start scale-y-[1.25] xxs:text-sm 2xl:text-2xl">My life beyond development</p>
    </section>

    <section 
        class="flex lg:h-[53vh] lg:min-h-[275px] items-center justify-center 3xl:py-20 xxs:gap-5 3xl:gap-10 flex-col 3xl:px-96 xxs:px-10 md:px-20 xl:px-45 bg-gray-200 xxs:h-[58vh] xxs:min-h-[375px] 3xl:h-[46vh] 2xl:min-h-[300px] 3xl:min-h-[310px] text-[rgba(4,47,46,1)] tracking-wider"
    >

        <p 
            class="2xl:text-sm xxs:text-xs"
        >
            Welcome to my hobbies section! This is where I showcase my creativity and the things I enjoy doing in my free time. Whether it's exploring new ideas, experimenting with different techniques, or simply creating for fun, each piece reflects my passion for self-expression. Feel free to explore and see what inspires me!
        </p>
    </section>

    <section class="flex flex-col items-center xxs:justify-center xxs:gap-16 xl:gap-10 xl:justify-between bg-teal-950 min-h-screen 3xl:px-96 xxs:px-10 md:px-20 xl:px-45 xxs:py-10 xl:py-28">

        <h2 class="text-orange-800 brightness-125 font-bold xxs:text-xl lg:text-3xl md:text-2xl 3xl:text-4xl tracking-widest">My Hobbies</h2>

        <section class="w-full flex flex-col text-orange-800 gap-5 items-center justify-evenly">

            <h3 class="brightness-125 font-bold xxs:text-base lg:text-lg 3xl:text-xl tracking-widest self-start">Photography</h3>

            <p class="brightness-125 tracking-wider text-gray-300 xl:text-sm xxs:text-xs xxs:w-full xl:w-[75%] self-start">I focus on mobile photography, using my phone to capture images in my daily life. This allows me to explore different subjects and environments, documenting moments as I encounter them. Mobile photography offers convenience and flexibility, helping me experiment with different techniques and perspectives.</p>

            <ul class="xl:grid xxs:flex flex-col items-center justify-evenly grid-cols-3 xxs:gap-2 xl:w-full place-items-center md:w-[85%] lg:w-[70%] lg:gap-5 xl:gap-2">
                <li class="w-full rounded-lg ">
                    <img 
                    class="xl:min-h-[144px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xxs:min-h-[164px] xs:h-[25vh] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover overflow-hidden object-[center_100%] cursor-pointer" 
                    loading="lazy" 
                    src="/img/photography/photograph_1.webp" >
                </li>

                <li class="w-full rounded-lg ">
                    <img 
                    class="xl:min-h-[144px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xxs:min-h-[164px] xs:h-[25vh] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover overflow-hidden object-[center_100%] cursor-pointer" 
                    loading="lazy" 
                    src="/img/photography/photograph_2.webp" >
                </li>
                
                <li class="w-full rounded-lg ">
                    <img 
                    class="xl:min-h-[144px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xxs:min-h-[164px] xs:h-[25vh] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover overflow-hidden object-[center_100%] cursor-pointer" 
                    loading="lazy" 
                    src="/img/photography/photograph_3.webp">
                </li>

            </ul>

        </section>

        <section class="w-full flex flex-col text-orange-800 gap-5 min-h-1/3 items-center justify-evenly">

            <h3 class="brightness-125 self-end font-bold xxs:text-base lg:text-lg 3xl:text-xl tracking-widest">Photo Manipulation</h3>

            <p class="brightness-125 tracking-wider text-gray-300 xxs:text-xs xl:text-sm xxs:w-full xl:w-[75%] self-end">I enjoy transforming ordinary images into something unique through editing. By adjusting colors, blending elements, and adding creative effects, I experiment with different techniques to bring new ideas to life. It's a way to push the limits of imagination and create visuals that go beyond what the camera captures.</p>

            <ul class="xl:grid xxs:flex flex-col items-center justify-evenly grid-cols-5 xl:gap-2 xl:w-full place-items-center xxs:gap-2 md:w-[85%] lg:w-[70%] lg:gap-5">
                <li class="w-full rounded-lg">
                    <img class="xl:min-h-[144px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover overflow-hidden xl:object-[center_50%] xxs:object-[center_47%] cursor-pointer" 
                    loading="lazy" 
                    src="/img/photomani/photoMani_1.webp">
                </li>

                <li class="w-full rounded-lg">
                    <img class="xl:min-h-[144px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover overflow-hidden object-[center_100%] cursor-pointer" 
                    loading="lazy" 
                    src="/img/photomani/photoMani_2.webp">
                </li>
                
                <li class="w-full rounded-lg">
                    <img 
                    style="object-position: 57% 20%;"
                    class="xl:min-h-[144px] xl:h-[25vh] xxs:h-[20vh] lg:h-[30vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover overflow-hidden object-[center_100%] cursor-pointer" 
                    loading="lazy"
                    src="/img/photomani/photoMani_3.webp"
                    >
                </li>

                <li class="w-full rounded-lg">
                    <img 
                    style="object-position: 73% 20%;"
                    class="xl:min-h-[144px] xl:h-[25vh] xxs:h-[20vh] lg:h-[30vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg overflow-hidden shadow-lg object-cover cursor-pointer" 
                    loading="lazy" 
                    src="/img/photomani/photoMani_4.webp">
                </li>

                <li class="w-full rounded-lg">
                    <img
                    style="object-position: 0 20%;" 
                    class="xl:min-h-[144px] xl:h-[25vh] xxs:h-[20vh] lg:h-[30vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg xl:overflow-hidden shadow-lg object-cover object-center cursor-pointer" 
                    loading="lazy" 
                    src="/img/photomani/photoMani_5.webp">
                </li>

            </ul>

        </section>

        <section class="w-full flex flex-col text-orange-800 gap-5 min-h-1/3 items-center justify-evenly">

            <h3 class="brightness-125 font-bold xxs:text-base lg:text-lg 3xl:text-xl tracking-widest">Short Films</h3>

            <p class="brightness-125 tracking-wider text-gray-300 xl:text-sm xxs:text-xs xxs:w-full xl:w-[75%]">Filmmaking allows me to tell stories through motion and sound. Whether it's capturing real moments or creating scripted scenes, I explore different ways to convey emotions and ideas. From planning shots to editing the final cut, every step is an opportunity to bring creativity to life.</p>

            <ul class="xl:grid xxs:flex flex-col items-center justify-evenly grid-cols-2 xxs:gap-2 xl:gap-12 place-items-center md:w-[85%] lg:w-[70%] lg:gap-5 xl:w-full">
                <li class="w-full rounded-lg">
                    <img class="xl:min-h-[144px] 2xl:min-h-[200px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg shadow-lg object-cover cursor-pointer overflow-hidden object-[center_50%]" 
                    loading="lazy" 
                    src="/img/shortfilm/short_film_1.png">
                </li>

                <li class="w-full rounded-lg">
                    <img class="xl:min-h-[144px] 2xl:min-h-[200px] xl:h-[25vh] lg:h-[30vh] xxs:h-[20vh] xs:h-[25vh] xxs:min-h-[164px] xs:min-h-[190px] w-full rounded-lg cursor-pointer shadow-lg object-cover overflow-hidden object-[center_100%]" 
                    loading="lazy" 
                    src="/img/shortfilm/short_film_2.png">
                </li>

            </ul>

        </section>

    </section>

</section>

// final/jon-arbell-de-ocampo-portfolio-frontend/app/pages/hobbies/index.vue
<template>
  <div>
    <Custom :image="'/img/photography/photograph_3.webp'">
      <Head
        :title="'My Hobbies'"
        :description="`Explore Jon's projects, tech stack, and resume. Specializing in Nuxt, Angular, Spring Boot and Laravel.`"
      />

      <section>
        <div>
          <Hero
            :subtitle="'Capturing stories through film, photos, and creativity'"
            :title="`Life Beyond the Code`"
            :style="'bg-gray-200/90'"
          />
        </div>
      </section>

      <section>
        <div
          class="flex items-center justify-center gap-10 xl:gap-4 flex-col xl:flex-row h-80 xl:h-96 bg-gray-50 w-full px-4 py-10 xl:px-52"
        >
          <p class="text-xs 2xl:text-sm tracking-widest text-teal-950">
            Welcome to my hobbies section! This is where I showcase my
            creativity and the things I enjoy doing in my free time. Whether
            it's exploring new ideas, experimenting with different techniques,
            or simply creating for fun, each piece reflects my passion for
            self-expression. Feel free to explore and see what inspires me!
          </p>
        </div>
      </section>

      <section>
        <div
          class="flex items-center tracking-widest text-xs 2xl:text-sm min-h-96 gap-10 flex-col justify-center w-full p-15 px-4 xl:px-52 bg-teal-950"
        >
          <h2 class="text-orange-700 text-xl font-semibold">My Hobbies</h2>

          <div class="space-y-4">
            <h3 class="text-orange-700 text-lg">Photography</h3>
            <p>
              I focus on mobile photography, using my phone to capture images in
              my daily life. This allows me to explore different subjects and
              environments, documenting moments as I encounter them. Mobile
              photography offers convenience and flexibility, helping me
              experiment with different techniques and perspectives.
            </p>
            <div>
              <ul
                class="flex items-center justify-center flex-col xl:flex-row gap-5 w-full"
              >
                <li
                  class="flex-1"
                  v-for="(item, index) in photography"
                  :key="index"
                >
                  <NuxtImg
                    :class="[
                      'rounded-xl shadow-xl hover:scale-105 transition-all duration-300',
                    ]"
                    :src="`/img/photography/${item}`"
                  />
                </li>
              </ul>
            </div>
          </div>

          <div class="space-y-4">
            <h3 class="text-orange-700 text-lg text-end">Photo Manipulation</h3>
            <p>
              I enjoy transforming ordinary images into something unique through
              editing. By adjusting colors, blending elements, and adding
              creative effects, I experiment with different techniques to bring
              new ideas to life. It's a way to push the limits of imagination
              and create visuals that go beyond what the camera captures.
            </p>
            <div>
              <ul class="flex flex-col xl:flex-row gap-5 w-full">
                <li
                  v-for="(item, index) in photomanipulation"
                  :key="index"
                  class="flex-1 flex"
                >
                  <NuxtImg
                    class="rounded-xl shadow-xl hover:scale-105 transition-all duration-300 w-full h-40 object-cover"
                    :src="`/img/photomani/${item}`"
                  />
                </li>
              </ul>
            </div>
          </div>

          <div class="space-y-4">
            <h3 class="text-orange-700 text-lg text-center">Short Films</h3>
            <p>
              Filmmaking allows me to tell stories through motion and sound.
              Whether it's capturing real moments or creating scripted scenes, I
              explore different ways to convey emotions and ideas. From planning
              shots to editing the final cut, every step is an opportunity to
              bring creativity to life.
            </p>
            <div>
              <ul
                class="flex items-center justify-center flex-col xl:flex-row gap-5 w-full"
              >
                <li
                  v-for="(item, index) in shortFilms"
                  :key="index"
                  class="flex-1"
                >
                  <NuxtImg
                    class="rounded-xl shadow-xl hover:scale-105 transition-all duration-300"
                    :src="`/img/shortfilm/${item}`"
                  />
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </Custom>
  </div>
</template>

<script lang="ts" setup>
import Head from "~/components/Head.vue";
import Custom from "~/layouts/Custom.vue";

const photography = [
  "photograph_1.webp",
  "photograph_2.webp",
  "photograph_3.webp",
];

const photomanipulation = [
  "photoMani_1.webp",
  "photoMani_2.webp",
  "photoMani_3.webp",
  "photoMani_4.webp",
  "photoMani_5.webp",
];

const shortFilms = ["short_film_1.png", "short_film_2.png"];
</script>

<style></style>
