// src/app/main/skills/skills.component.ts
import { Component } from '@angular/core';
import { TitleService } from '../../service/title.service';

@Component({
  selector: 'app-skills',
  standalone: true,
  imports: [],
  templateUrl: './skills.component.html'
})
export class SkillsComponent {

  stacks : TechStacks[] = [
    new TechStacks('Java 23','assets/img/java.png'),
    new TechStacks('Spring Boot 3','assets/img/spring.png'),
    new TechStacks('PostgreSQL','assets/img/postgresql.png'),
    new TechStacks('JavaScript','assets/img/js.png'),
    new TechStacks('TypeScript','assets/img/ts.png'),
    new TechStacks('Angular 19','assets/img/angular.png'),
    new TechStacks('CSS','assets/img/css-3.png'),
    new TechStacks('Tailwind CSS','assets/img/tailwind.png'),
    new TechStacks('GitHub','assets/img/github.png')
  ];

}

class TechStacks{
  constructor(private techName : string,private imagePath : string) {}

  getTechName() : string{
    return this.techName;
  }

  getImagePath() : string{
    return this.imagePath;
  }
}
<section class="flex items-center justify-center h-[80vh] bg-gradient-to-br from-gray-800 via-orange-950 text-[#bebebe] to-gray-800 px-8 md:px-16 lg:px-40">
    <div class="w-full">

        <div class="xs:mb-5 xl:mb-7 3xl:mb-10">
            <h2 class="text-center font-bold xs:text-xl lg:text-3xl md:text-2xl 3xl:text-4xl text-[#bebebe] 2xl:mb-4 tracking-wider mb-5">My Tech Stack</h2>
            <p class="xl:mb-7 tracking-wide xs:text-xs 2xl:text-base xs:mb-2 text-center">The technologies I work with to bring ideas to life.</p>
        </div>

        <ul class="grid xs:place-items-center 3xl:grid-cols-9 xs:grid-cols-3 w-full mb-10 xs:gap-4">
            <li class=" 3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/java.png" alt="Java icon">

                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">Java</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/spring.256x256.png" alt="Spring Boot icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">Spring Boot</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/postgresql-plain.248x256.png" alt="PostgreSql icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">PostgreSQL</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/angular.png" alt="Angular icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">Angular</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/typescript.png" alt="TypeScript icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">TypeScript</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xxs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/js.png" alt="JavaScript icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">JavaScript</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/css-3.png" alt="CSS 3 icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">CSS 3</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/tailwind.png" alt="Tailwind css icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">Tailwind CSS</p>
            </li>

            <li class="3xl:h-40 3xl:w-36 xs:w-20 xs:h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 xl:w-32 xl:h-32 2xl:h-36 2xl:w-36 flex flex-col items-center justify-center p-4 rounded-xl bg-gray-300 shadow-2xl">
                <img class="mb-2 xs:h-7 xs:w-7 3xl:h-20 3xl:w-20 hover:scale-110 transition-transform duration-200" src="assets/img/github.png" alt="GitHub icon">
                <p class="text-center text-zinc-900 xs:text-xs 3xl:text-base">GitHub</p>
            </li>
        </ul>

        
    </div>
</section>

// app/pages/skills/index.vue
<template>
  <div>
    <Custom :image="'/img/photography/photograph_2.webp'">
      <Head
        :title="'My Tech Stack'"
        :description="`Explore Jon's projects, tech stack, and resume. Specializing in Nuxt, Angular, Spring Boot and Laravel.`"
      />

      <!-- Hero Section -->
      <section>
        <Hero
          :subtitle="'The technologies behind the solutions'"
          :title="`My Tools of Choice`"
          :style="'bg-gray-200/90'"
        />
      </section>

      <!-- About Section -->
      <section>
        <div
          class="flex items-center text-xs xl:text-sm tracking-widest justify-center flex-col gap-5 text-teal-950 h-80 xl:h-96 bg-gray-50 w-full px-4 py-10 xl:px-52"
        >
          <h2 class="text-xl font-semibold">What I Do</h2>
          <p>
            I focus on building full-stack applications with a strong foundation
            in backend and frontend development. On the backend, I work with
            <span class="font-medium">Spring Boot</span> and
            <span class="font-medium">Laravel</span> to create secure, scalable,
            and efficient systems. On the frontend, I specialize in
            <span class="font-medium">Nuxt</span> and
            <span class="font-medium">Angular</span>
            to deliver modern, responsive, and user-friendly applications. My
            goal is to write clean, maintainable code, follow best practices,
            and create impactful software that drives efficiency and innovation.
          </p>
        </div>
      </section>

      <!-- Tech Stacks Section -->
      <section>
        <div
          class="bg-teal-950 text-white p-20 min-h-96 flex-col flex items-center justify-center gap-10"
        >
          <h2 class="text-xl text-center font-semibold">My Tech Stacks</h2>

          <ul
            class="grid grid-cols-2 gap-10 justify-items-center md:grid-cols-3 xl:grid-cols-4 text-xs 2xl:text-sm"
          >
            <li
              v-for="(tech, index) in techStack"
              :key="tech.name"
              class="rounded-lg text-center bg-zinc-800 shadow-xl hover:scale-110 transition-all duration-300 p-5 flex items-center gap-4 justify-center flex-col h-28 w-28"
            >
              <Motion
                :initial="{ opacity: 0, scale: 0.8 }"
                :while-in-view="{ opacity: 1, scale: 1 }"
                :transition="{
                  duration: 0.6,
                  ease: 'easeInOut',
                  delay: index * 0.1,
                }"
                :viewport="{ once: true }"
                class="flex flex-col items-center justify-center"
              >
                <NuxtImg
                  class="h-10"
                  :src="`/img/${tech.icon}`"
                  :alt="tech.name"
                />
                <span>{{ tech.name }}</span>
              </Motion>
            </li>
          </ul>
        </div>
      </section>
    </Custom>
  </div>
</template>

<script lang="ts" setup>
import Head from "~/components/Head.vue";
import Custom from "~/layouts/Custom.vue";

const techStack = [
  {
    name: "Spring Boot",
    icon: "spring.png",
  },
  {
    name: "Java",
    icon: "java.png",
  },
  {
    name: "Nuxt",
    icon: "nuxt.png",
  },
  {
    name: "Angular",
    icon: "angular.png",
  },
  {
    name: "Laravel",
    icon: "laravel.png",
  },
  {
    name: "PHP",
    icon: "php.png",
  },
  {
    name: "TypeScript",
    icon: "ts.png",
  },
  {
    name: "JavaScript",
    icon: "js.png",
  },
  {
    name: "Tailwind CSS",
    icon: "tailwind.png",
  },
  {
    name: "PostgreSQL",
    icon: "postgresql.png",
  },
  {
    name: "MySQL",
    icon: "mysql.png",
  },
  {
    name: "GitHub",
    icon: "github.png",
  },
  {
    name: "Postman",
    icon: "postman.png",
  },
];
</script>

<style></style>
