// app/components/Footer.vue
<template>
  <footer class="bg-zinc-900 text-zinc-200 px-6 py-12">
    <div
      class="w-full mx-auto flex flex-col xl:flex-row justify-between items-center gap-10"
    >
      <!-- Left Brand / Tagline -->
      <div class="text-center space-y-2">
        <h3 class="tracking-widest font-bold text-xl text-orange-800">
          Keep Exploring
        </h3>
      </div>

      <!-- Divider -->
      <hr class="bg-white border-0 w-full h-px xl:w-px xl:h-20 opacity-30" />

      <!-- Middle Nav -->
      <div class="text-center">
        <nav>
          <ul
            class="flex flex-col xl:flex-row gap-4 xl:gap-6 text-xs font-medium"
          >
            <li>
              <NuxtLink
                to="/"
                class="hover:text-orange-500 transition-colors duration-300"
              >
                Home
              </NuxtLink>
            </li>
            <li v-for="(nav, index) in navStore.navs" :key="index">
              <NuxtLink
                :to="nav.link"
                class="hover:text-orange-500 transition-colors duration-300"
              >
                {{ nav.name }}
              </NuxtLink>
            </li>
          </ul>
        </nav>
        <div class="mt-4 text-xs text-zinc-500 space-y-2">
          <p>&copy; {{ new Date().getFullYear() }} Jon Arbell De Ocampo</p>
          <p>All rights reserved.</p>
        </div>
      </div>

      <!-- Divider -->
      <hr class="bg-white border-0 w-full h-px xl:w-px xl:h-20 opacity-30" />

      <!-- Right Socials -->
      <div class="text-center xl:text-right space-y-4">
        <ul class="flex justify-center gap-5">
          <li
            v-for="(social, index) in socials"
            :key="index"
            class="hover:scale-110 transition-transform"
          >
            <NuxtLink
              :to="social.link"
              target="_blank"
              rel="noopener noreferrer"
            >
              <NuxtImg
                :src="social.img"
                :alt="social.name"
                class="h-8 w-8 rounded-full hover:border-orange-500 transition-colors"
              />
            </NuxtLink>
          </li>
        </ul>
        <p class="text-sm text-zinc-400">
          <a
            href="mailto:deocampo.arbelldonor@gmail.com"
            class="hover:text-orange-500 transition-colors"
          >
            deocampo.arbelldonor@gmail.com
          </a>
        </p>
      </div>
    </div>
  </footer>
</template>

<script lang="ts" setup>
const navStore = useMyNavigationsStore();

const socials = [
  {
    name: "GitHub",
    link: "",
    img: "/img/github_icon.png",
  },
  {
    name: "LinkedIn",
    link: "",
    img: "/img/linkedin_icon.png",
  },
  {
    name: "Instagram",
    link: "",
    img: "/img/instagram.png",
  },
];
</script>

<style></style>

// src/app/main/footer/footer.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  imports: [RouterLink, CommonModule],
  templateUrl: './footer.component.html'
})
export class FooterComponent {
  @Input() isUriInHeroSection: boolean = false;
}

<section [ngClass]="isUriInHeroSection ? 'hidden' : 'flex'"
id="footer" class="transition-all ease-in-out items-center justify-center xxs:h-[93.5vh] xxs:min-h-[550px] lg:h-[20vh] lg:min-h-[164px] 2xl:px-40 xxs:px-10 bg-zinc-900 ">

  <section class="lg:flex items-center gap-5 text-gray-300 lg:w-full">
    <h3 class="text-xl 2xl:text-2xl 3xl:text-3xl font-black tracking-widest text-center">Keep Exploring</h3>

    <hr class="h-px bg-gray-300 rotate-0 lg:rotate-90 lg:h-full lg:w-24 lg:mx-4 my-10 lg:my-0">

    <div class="lg:flex items-center justify-between w-full h-full">

      <nav class="lg:w-[60%] 2xl:w-[55%] w-full">
        <ul class="flex items-center lg:flex-row flex-col gap-5 w-full mb-10 lg:mb-4 tracking-wide text-xs xl:text-sm">

          <li>
            <a class="hover:underline" routerLink="/">Home</a>
          </li>

          <li>
            <a class="hover:underline" routerLink="about-me">About Me</a>
          </li>

          <li>
            <a class="hover:underline" routerLink="personal-projects">Projects</a>
          </li>

          <li>
            <a class="hover:underline" routerLink="skills">Skills</a>
          </li>

          <li>
            <a class="hover:underline" routerLink="hobbies">Hobbies</a>
          </li>

          <li>
            <a class="hover:underline" routerLink="contact-me">Contact Me</a>
          </li>

        </ul>

        <div class="mb-10 lg:mb-0 tracking-wide lg:justify-start justify-center w-full flex flex-wrap items-center gap-4 text-xs xl:text-sm">
          <p>&copy; 2025 Jon Arbell De Ocampo.</p>
          <p>All right reserved.</p>
        </div>

      </nav>



      <div class="flex flex-col justify-around h-full text-center lg:text-left">
        <ul class="flex flex-wrap items-center gap-5 justify-center mb-3 ">
          <li>
            <a href="https://github.com/JonArbell" target="_blank">
              <img src="/img/github_icon.png" alt="GitHub" class="h-7 w-7 lg:h-6 lg:w-6 2xl:h-8 2xl:w-8 rounded-3xl">
            </a>
          </li>
          <li>
            <a href="https://www.linkedin.com/in/jon-arbell-donor-de-ocampo-134083284/" target="_blank">
              <img src="/img/linkedin_icon.png" alt="LinkedIn" class="h-7 w-7 lg:h-6 lg:w-6 2xl:h-8 2xl:w-8 rounded-3xl">
            </a>
          </li>
          <li>
            <a href="https://www.instagram.com/j_arbelldeocampo/" target="_blank">
              <img src="/img/instagram.png" alt="LinkedIn" class="h-7 w-7 lg:h-6 lg:w-6 2xl:h-8 2xl:w-8 rounded-3xl">
            </a>
          </li>
        </ul>
        <div class="tracking-wide flex flex-wrap items-center gap-4 justify-center text-xs xl:text-sm">
          <p>{{'deocampo.arbelldonor@gmail.com'}}</p>
        </div>

      </div>
    </div>



  </section>



    <!-- <section class="text-red-700 font-bold text-center">
        <h2 class="xs:text-xl lg:text-3xl lg:text-2xl 3xl:text-4xl 2xl:mb-4 tracking-wider mb-5">Footer</h2>
        <h1>UNDER CONSTRUCTION</h1>
    </section> -->

</section>
