// src/app/main/about-me/about-me.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about-me',
  imports: [],
  templateUrl: './about-me.component.html'
})
export class AboutMeComponent {

}


<!-- <section id="about-me" class="3xl:px-40 bg-gradient-to-br from-black via-zinc-900 flex to-gray-800 xs:flex-col xl:justify-around xs:justify-center xs:gap-4 md:gap-0 lg:flex-row items-center h-[90%]">

    <section class="lg:w-1/2 xs:h-1/3 lg:h-1/2 xl:h-full xs:py-2 xl:py-4 flex items-center justify-center">
        
        <img class="3xl:h-[85%] xs:h-full hover:scale-110 transition-transform duration-300 ease-in-out" src='assets/img/about-me.png' alt="My Pictures">

    </section>

    <section class="flex flex-col justify-center text-[#bebebe] xs:w-full xl:w-1/2 xl:p-14  xl:h-full xs:px-10">
        <h2 class="font-bold xs:text-base xl:text-lg 3xl:text-xl xs:mb-2 xl:mb-3">About Me</h2>

        <h1 class="font-bold xs:text-lg md:text-2xl 2xl:text-3xl 3xl:text-4xl xs:mb-2 3xl:mb-7 tracking-wider text-orange-700">Jon Arbell De Ocampo</h1>

        <p class="xl:mb-7 tracking-wide xs:text-xs 2xl:text-base xs:mb-2">A 3rd-year Computer Science student with a strong focus on backend development. I specialize in building scalable applications using Spring Boot, Spring Security, and Spring MVC, with a solid foundation in designing REST APIs. While my primary expertise is in backend development, I'm currently exploring Angular to enhance my frontend skills.</p>

        <p class="tracking-wide xs:text-xs 2xl:text-base">I enjoy solving technical challenges and writing clean, maintainable code. Outside of coding, I express my creativity through photography, photo manipulation, video editing, and short film making. Check out my projects, and feel free to reach out for collaboration!</p>

    </section>

    
</section> -->

<section class="text-white xs:gap-4 md:gap-0">

    <section class="3xl:p-40  bg-gray-200/70 text-center 3xl:h-[45vh] xs:h-[40vh] xs:flex items-center justify-center flex-col 3xl:block leading-relaxed">
        <h1 class="xs:text-lg md:text-2xl 2xl:text-3xl 3xl:text-4xl xs:mb-2 3xl:mb-7 tracking-wider text-orange-700 scale-y-150">From Learning to Mastery: A Developer's Story</h1>
        <p class="text-[rgba(4,47,46,1)] scale-y-[1.25]">Jon Arbell De Ocampo</p>
    </section>

    <section class="3xl:px-96 xs:px-10 xs:flex-col xl:justify-around xs:justify-center items-center bg-gray-200 tracking-widest flex lg:flex-row xs:gap-4 md:gap-10 3xl:h-[45vh] xs:h-[90vh]">
        
        <section class="lg:w-1/2 xs:h-1/3 lg:h-1/2 xl:h-full xs:py-2 xl:py-4 flex items-center justify-center">
        
            <img class="3xl:h-[60%] xs:h-full hover:scale-110 transition-transform duration-300 ease-in-out" src='assets/img/about-me.png' alt="My Pictures">
    
        </section>

        <section class="3xl:text-sm tracking-widest text-[rgba(4,47,46,1)] xs:text-xs leading-relaxed">
            <p class="mb-4">Hello, I'm Jon Arbell De Ocampo, a 3rd-year Computer Science student with a strong focus on backend development. I specialize in building scalable applications using Spring Boot, Spring Security, and Spring MVC, with a solid foundation in designing REST APIs. While my primary expertise is in backend development, I'm currently exploring Angular to enhance my frontend skills.</p>

            <p>I enjoy solving technical challenges and writing clean, maintainable code. Outside of coding, I express my creativity through photography, photo manipulation, video editing, and short film making. Check out my projects, and feel free to reach out for collaboration!</p>
        </section>
    </section>

    <section class="3xl:p-40 xs:px-10 3xl:block flex items-center flex-col gap-2 justify-center xs:text-xs 3xl:px-96 3xl:text-sm bg-orange-900 tracking-widest leading-relaxed text-gray-300 3xl:h-[50vh] xs:h-[35vh]">
        <h2 class="3xl:text-3xl xs:text-xl mb-4">Overview</h2>

        <hr class="mb-4 bg-gray-300 border-0 h-[1px] w-full">

        <p>Technology is constantly evolving, and so am I. My journey as a developer is fueled by curiosity, problem-solving, and the drive to create meaningful software solutions. From backend architecture to frontend exploration, I embrace every challenge as an opportunity to grow. My goal is to build applications that are not just functional but also efficient, scalable, and impactful.</p>
    </section>

    <section class="3xl:px-96 xs:p-10 3xl:py-0 bg-zinc-800 flex flex-col gap-10 w-full justify-center items-center 3xl:h-[95vh] xs:min-h-screen">
        <section class="flex items-center xs:flex-col 3xl:flex-row 3xl:gap-24 xs:gap-2">

            <section class="tracking-widest text-gray-300 3xl:text-sm xs:text-xs leading-relaxed">
                <h2 class="text-orange-700 3xl:text-3xl xs:text-xl xs:mb-2 3xl:mb-4">A Developer's Journey</h2>

                <hr class="border-0 h-[1px] bg-orange-700 3xl:mb-4 xs:mb-2">

                <p class="xs:mb-2 3xl:mb-0">I still remember the first time I wrote a program that actually worked. It was a simple C++ script, but the excitement of solving a problem through code was unforgettable. That moment sparked my journey of continuous learning—from writing basic programs to developing scalable applications with Spring Boot. Now, every challenge I encounter is another opportunity to grow. Coding isn't just a skill to me — it's a mindset.</p>
            </section>

            <section class="3xl:w-[72%] xs:w-full 3xl:block xs:flex flex-col items-center justify-center gap-2">
                <img class="h-[30vh] rounded-lg" src="/icon.png">
                <p class="text-orange-700 text-center leading-relaxed">Jon Arbell De Ocampo</p>
            </section>

        </section>

        <section class="flex items-center xs:flex-col-reverse 3xl:flex-row 3xl:gap-24 xs:gap-2">

            <section class="3xl:w-[62%] xs:w-full xs:flex flex-col items-center justify-center gap-2">
                <img class="h-[30vh] rounded-lg" src="/icon.png">
                <p class="text-orange-700 text-center leading-relaxed">Jon Arbell De Ocampo</p>
            </section>

            
            <section class="tracking-widest text-gray-300 3xl:text-sm xs:text-xs leading-relaxed">

                <h2 class="text-orange-700 3xl:text-3xl xs:text-xl 3xl:mb-4 xs:mb-2">The Problem-Solver's Mindset</h2>

                <hr class="border-0 h-[1px] bg-orange-700 3xl:mb-4 xs:mb-2">

                <p class="xs:mb-2 3xl:mb-0">Every bug is a puzzle, and every system issue is a challenge waiting to be solved. As a backend developer, I've learned that the best solutions aren't always the easiest ones—they're the ones that scale, perform, and stand the test of time. My approach to coding is simple: write clean, maintainable, and efficient solutions that make an impact.</p>
                
            </section>

        </section>
    </section>

    <section class="3xl:px-72 xs:p-10 3xl:py-0 xs:min-h-screen  3xl:h-[60vh] bg-gray-200 xs:flex-col 3xl:flex-row tracking-widest text-orange-700 flex items-center xs:justify-center gap-4">
        <section class="3xl:text-sm xs:text-xs bg-zinc-800 xs:w-full rounded-lg leading-relaxed shadow-lg h-[75%] 3xl:w-[30%] p-4">
            <h3 class="scale-y-125 3xl:text-2xl xs:text-lg mb-4 text-center">MISSION</h3>
            <ul class="text-gray-300 list-disc pl-5">
                <li class="mb-4">Short-term Mission: My immediate goal is to deepen my expertise in full-stack development and to build impactful web applications using cutting-edge technologies like Spring Boot and Angular.</li>
                <li>Long-term Mission: In the long run, I want to contribute to innovative software solutions that address real-world problems, whether through freelancing, working with a forward-thinking company, or even starting my own tech venture.</li>
            </ul>
        </section>

        <section class="3xl:text-sm xs:text-xs xs:w-full bg-zinc-800 leading-relaxed rounded-lg shadow-lg h-[75%] 3xl:w-[30%] p-4">
            <h3 class="scale-y-125 3xl:text-2xl xs:text-lg mb-4 text-center">CORE VALUES</h3>
            <ul class="text-gray-300 list-disc pl-5">
                <li class="mb-4">I believe that every problem is an opportunity to learn. My journey in programming has taught me that consistency and dedication are the keys to growth.</li>
                <li>I value teamwork and believe that great things happen when we share knowledge, challenge each other, and work together toward a common goal.</li>
            </ul>
        </section>

        <section class="3xl:text-sm xs:text-xs xs:w-full bg-zinc-800 leading-relaxed rounded-lg shadow-lg h-[75%] 3xl:w-[30%] p-4">
            <h3 class="scale-y-125 3xl:text-2xl xs:text-lg mb-4 text-center">PHILOSOPHY</h3>
            <p class="text-gray-300">I see programming as a never-ending learning process. Each new concept I learn is like unlocking a new level of understanding, and I embrace challenges as opportunities to evolve. I believe in writing clean, maintainable code that not only solves problems but is also easy for others to understand and build upon.</p>
        </section>
    </section>
</section>

// app/pages/about-me/index.vue
<template>
  <div>
    <Custom :image="'/img/cover-hero-section.png'">
      <Head
        :title="'About Me'"
        :description="`Explore Jon's projects, tech stack, and resume. Specializing in Nuxt, Angular, Spring Boot and Laravel.`"
      />

      <!-- Hero Section -->
      <section>
        <div>
          <Hero
            :subtitle="'Driven by curiosity, grounded in code'"
            :title="`From Learning to Mastery: A Developer's Story`"
            :style="'bg-gray-200/90'"
          />
        </div>
      </section>

      <!-- Intro Section -->
      <section>
        <div
          class="flex items-center justify-center gap-10 xl:gap-4 flex-col-reverse xl:flex-row xl:h-96 bg-gray-50 max-w-full px-4 py-10 xl:px-52"
        >
          <!-- Text Motion -->
          <Motion
            class="flex-1 text-xs 2xl:text-sm tracking-widest text-teal-950 flex justify-center items-center"
            :initial="{ opacity: 0, x: -60 }"
            :while-in-view="{ opacity: 1, x: 0 }"
            :transition="{ duration: 0.6, ease: 'easeInOut' }"
            :viewport="{ once: true, amount: 0.4 }"
          >
            <p>
              I’m deeply passionate about backend development, having started my
              journey with Java Spring Boot where I focused on building secure,
              scalable systems and efficient REST APIs. Although my career began
              on the frontend with Nuxt/Vue 3, that experience gave me a
              stronger appreciation for the full stack and how the backend
              connects with the user experience. Since August, I’ve been fully
              focused on backend work with Laravel, where I feel most at home
              architecting systems and optimizing performance. Beyond coding, I
              express creativity through photography, video editing, and short
              film making, which allow me to balance my technical work with
              artistic expression.
            </p>
          </Motion>

          <!-- Image Motion -->
          <Motion
            class="flex-1 flex justify-center items-center"
            :initial="{ opacity: 0, scale: 0.8 }"
            :while-in-view="{ opacity: 1, scale: 1 }"
            :transition="{ duration: 0.6, ease: 'easeInOut', delay: 0.2 }"
            :viewport="{ once: true }"
          >
            <NuxtImg
              alt="Jon Arbell De Ocampo_Itomori"
              class="h-56 rounded-lg hover:scale-105 transition-all duration-300"
              src="/img/arbell_3.webp"
            />
          </Motion>
        </div>
      </section>

      <!-- Overview -->
      <section>
        <div
          class="flex flex-col items-center text-xs 2xl:text-sm text-white gap-4 xl:h-96 bg-orange-900 max-w-full px-4 xl:px-52 py-16"
        >
          <h2 class="font-semibold text-xl">Overview</h2>

          <hr class="w-[25%] border-2 rounded-full" />

          <p class="text-center max-w-2xl">
            Adaptability and innovation drive my journey as a developer. I
            specialize in backend architecture while exploring frontend
            technologies to build seamless, high-performing applications. Every
            challenge is an opportunity to refine my skills, optimize systems,
            and create impactful solutions.
          </p>
        </div>
      </section>

      <!-- Journey + Problem-Solver -->
      <section class="bg-zinc-900 max-w-full">
        <!-- Journey -->
        <div
          class="flex items-center gap-7 xl:flex-row flex-col justify-center max-w-full p-15 pb-0 px-4 xl:px-52"
        >
          <Motion
            class="flex flex-col flex-1 gap-4 tracking-widest text-xs 2xl:text-sm"
            :initial="{ opacity: 0, x: -60 }"
            :while-in-view="{ opacity: 1, x: 0 }"
            :transition="{ duration: 0.7, ease: 'easeInOut' }"
            viewport="{ once: true, amount: 0.5 }"
          >
            <h2 class="text-orange-700 font-semibold text-xl">
              A Developer's Journey
            </h2>
            <hr
              class="border-2 border-b-orange-700 border-t-white rounded-full"
            />
            <p>
              I still remember the first time I wrote a program that actually
              worked. It was a simple C++ script, but the excitement of solving
              a problem through code was unforgettable. That moment sparked my
              journey of continuous learning—from writing basic programs to
              developing scalable applications with Spring Boot. Now, every
              challenge I encounter is another opportunity to grow. Coding isn't
              just a skill to me — it's a mindset.
            </p>
            <small class="text-orange-700"> Jon Arbell De Ocampo </small>
          </Motion>

          <Motion
            class="flex-1 items-center justify-center flex"
            :initial="{ opacity: 0, scale: 0.8 }"
            :while-in-view="{ opacity: 1, scale: 1 }"
            :transition="{ duration: 0.7, ease: 'easeInOut', delay: 0.2 }"
            :viewport="{ once: true }"
          >
            <NuxtImg
              class="h-72 rounded-xl hover:scale-110 shadow-xl transition-all duration-300"
              src="/img/arbell_1.png"
              alt="Jon Arbell De Ocampo_1"
            />
          </Motion>
        </div>

        <!-- Problem Solver -->
        <div
          class="flex items-center gap-7 xl:flex-row flex-col-reverse justify-center max-w-full p-15 px-4 xl:px-52"
        >
          <Motion
            class="flex-1 items-center justify-center flex"
            :initial="{ opacity: 0, scale: 0.8 }"
            :while-in-view="{ opacity: 1, scale: 1 }"
            :transition="{ duration: 0.7, ease: 'easeInOut' }"
            :viewport="{ once: true }"
          >
            <NuxtImg
              class="h-72 rounded-xl hover:scale-110 shadow-xl transition-all duration-300"
              src="/img/arbell_2.jpg"
              alt="Jon Arbell De Ocampo_2"
            />
          </Motion>

          <Motion
            class="flex flex-col flex-1 gap-4 tracking-widest text-xs 2xl:text-sm"
            :initial="{ opacity: 0, x: 60 }"
            :while-in-view="{ opacity: 1, x: 0 }"
            :transition="{ duration: 0.7, ease: 'easeInOut' }"
            :viewport="{ once: true, amount: 0.5 }"
          >
            <h2 class="text-orange-700 font-semibold text-xl">
              The Problem-Solver's Mindset
            </h2>
            <hr
              class="border-2 border-b-orange-700 border-t-white rounded-full"
            />
            <p>
              Every bug is a puzzle, and every system issue is a challenge
              waiting to be solved. As a backend developer, I've learned that
              the best solutions aren't always the easiest ones—they're the ones
              that scale, perform, and stand the test of time. My approach to
              coding is simple: write clean, maintainable, and efficient
              solutions that make an impact.
            </p>
            <small class="text-orange-700"> Jon Arbell De Ocampo </small>
          </Motion>
        </div>
      </section>

      <!-- Boxes -->
      <section>
        <div
          class="flex items-center gap-7 xl:flex-row flex-col-reverse justify-center max-w-full p-15 px-4 xl:px-52"
        >
          <ul
            class="grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 gap-4 items-stretch max-w-full"
          >
            <li v-for="(item, index) in boxes" :key="index" class="flex">
              <Motion
                :initial="{ opacity: 0, y: 40 }"
                :while-in-view="{ opacity: 1, y: 0 }"
                :transition="{
                  duration: 0.5,
                  ease: 'easeInOut',
                  delay: index * 0.15,
                }"
                :viewport="{ once: true }"
                class="flex-1"
              >
                <Box :title="item.title" :descriptions="item.descriptions" />
              </Motion>
            </li>
          </ul>
        </div>
      </section>
    </Custom>
  </div>
</template>

<script lang="ts" setup>
import Head from "~/components/Head.vue";
import Custom from "~/layouts/Custom.vue";
import Box from "./components/Box.vue";

const boxes = [
  {
    title: "MISSION",
    descriptions: [
      "Short-term: Deepen full-stack skills and build impactful applications with Spring Boot / Laravel & Nuxt / Angular.",
      "Long-term: Innovate real-world solutions — freelancing, a tech-driven company, or my own venture.",
    ],
  },
  {
    title: "CORE VALUES",
    descriptions: [
      "Problems are growth opportunities — consistency and curiosity fuel progress.",
      "Teamwork matters — I thrive in spaces that share, challenge, and collaborate.",
    ],
  },
  {
    title: "PHILOSOPHY",
    descriptions: [
      "Programming is a lifetime game of leveling up. Each challenge is a new level, every bug is a boss fight, and writing clean code is my cheat code for team success and project longevity.",
    ],
  },
];
</script>

<style></style>
